# Generated by Django 5.1.2 on 2025-02-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_category_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='introduction_video',
        ),
    ]
